# Generated by Django 3.1 on 2020-08-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contenido',
            field=models.TextField(default='El contenido va aqui'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=30),
        ),
    ]
