# Generated by Django 3.1 on 2020-08-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200827_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contra',
            new_name='contrasena',
        ),
    ]
