# Generated by Django 3.1 on 2020-08-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20200821_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='ranking',
            field=models.PositiveIntegerField(),
        ),
    ]
