# Generated by Django 3.1 on 2020-08-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
                ('ranking', models.TextField()),
                ('precio', models.TextField()),
            ],
        ),
    ]
