# Generated by Django 3.1 on 2020-08-25 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20200825_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='metros',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='material',
            name='glb',
        ),
    ]
