# Generated by Django 3.1 on 2020-08-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20200825_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
