# Generated by Django 3.1 on 2020-08-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseno',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='gld',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='imagen',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='numMateriales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='ranking',
            field=models.PositiveIntegerField(),
        ),
    ]
