# Generated by Django 3.1 on 2020-08-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0002_auto_20200821_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseno',
            old_name='precio',
            new_name='metros',
        ),
        migrations.RemoveField(
            model_name='diseno',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='diseno',
            name='numMateriales',
        ),
    ]
