# Generated by Django 3.1 on 2020-08-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0003_auto_20200825_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseno',
            old_name='gld',
            new_name='glb',
        ),
    ]
