# Generated by Django 3.1 on 2020-08-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAuto', models.PositiveIntegerField()),
                ('idDiseno', models.PositiveIntegerField()),
                ('idCotizacion', models.PositiveIntegerField()),
                ('idUsuario', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('idMaterial', models.PositiveIntegerField()),
            ],
        ),
    ]
