# Generated by Django 3.1 on 2020-08-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
        ('auto', '0003_auto_20200821_0019'),
        ('material', '0005_auto_20200826_0017'),
        ('diseno', '0003_auto_20200825_2345'),
        ('simulacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacion',
            name='idUsuario',
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='idAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.auto'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='idCotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizacion.cotizacion'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='idDiseno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diseno.diseno'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='idMaterial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.material'),
        ),
    ]
