# Generated by Django 3.1 on 2020-08-29 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200827_2122'),
        ('simulacion', '0002_auto_20200826_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='idUsuario',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario'),
        ),
    ]
